//! What the machine thinks the time is, and what it does when it cannot tell.
//!
//! The wall clock is one of the few devices the *host* can set, which is what
//! makes this checkable from outside the guest at all: `-rtc base=` puts a
//! known instant in the emulated CMOS before the machine starts, so the name
//! and the timestamp of the file the guest writes are both known before there
//! is a guest. Every verdict here is read off the disk image the device
//! received, never off anything the guest said about it — the boot log is used
//! only to say *why* a disagreement happened.
//!
//! # The year is 2101 on purpose
//!
//! A two-digit RTC year cannot express a century, so the century comes from a
//! separate CMOS register whose index the FADT names. Staging any year in the
//! 2000s would pass with that register ignored, because `2000 + year` is right
//! for the whole of this century — which is exactly why it went unnoticed that
//! the kernel read a hardcoded 0x32 and called it a guess in a comment. At 2101
//! the two answers differ by a hundred years and the file name says which one
//! the kernel computed.
//!
//! # What only a kernel feature can stage
//!
//! Three states of a broken clock, and QEMU can produce none of them: it has no
//! switch that removes or wedges the mc146818, its RTC always presents the
//! guest a coherent register set, and the FADT a guest reads is generated by
//! QEMU and always names the century register. Each is a `#[cfg(feature)]` in
//! `kernel/src/rtc.rs` or `drivers/acpi.rs` that changes what the *hardware*
//! answers, leaving the decoder and everything downstream of it shipped code —
//! including the file name, which is what these assert on.

use std::io::Write;
use std::path::Path;
use std::time::Duration;

use super::qemu::{self, BootOptions, QemuInstance};
use super::serial;
use super::volumes::{self, Entry};

/// What the host sets the emulated RTC to, and the same instant in seconds.
///
/// Past the year 2100 for the reason in the module docs. Inside FAT's range,
/// whose last representable day is 2107-12-31 — the file this boot writes has
/// to carry this instant as its own timestamp, and a clamp would hide the
/// difference between "the kernel read the century" and "the format could not
/// say".
const RTC_BASE: &str = "2101-06-05T04:03:02";
const RTC_BASE_SECS: i64 = 4_147_387_382;
/// What a file named for that instant begins with. The date and not the time,
/// because the seconds move on while the machine boots and
/// [`MAX_BOOT_DRIFT_SECS`] is what bounds that — the timestamp inside the entry
/// is where this is checked to the second.
const RTC_BASE_DATE: &str = "2101-06-05-";

/// How far past [`RTC_BASE`] the guest may have got by the time it names its
/// log file.
///
/// The guest's clock runs from the base at host speed, so this is a boot's own
/// wall-clock duration and nothing else — a machine that reaches its log sink
/// in under a second on a quiet host, and in a good deal more on a busy one.
/// Five minutes is three orders of magnitude above the former, which keeps this
/// from being a wall-clock margin the way the serial-tail tests' verdicts are:
/// nothing in the phase can slow a boot by that much, and a kernel that got the
/// century wrong is out by a hundred years rather than by seconds.
const MAX_BOOT_DRIFT_SECS: i64 = 300;

/// How many logs `log_file::MAX_LOG_FILES` keeps. Mirrored rather than shared,
/// so moving the kernel's bound without looking at this fails here rather than
/// quietly weakening the gate.
pub const MAX_LOG_FILES: usize = 16;

/// The name of the boot the guest must delete, and the ones it must not.
///
/// Sixteen staged files, so the volume is exactly at the bound before the guest
/// starts and this boot's own file is the one that puts it over. They are dated
/// 2098, before [`RTC_BASE`], so the one that has to go is unambiguous — and
/// they are *not* consecutive, so an implementation deleting "the first one it
/// listed" or "the lowest index" rather than the oldest lands on a different
/// file than the one asserted.
fn staged_logs() -> Vec<(String, Vec<u8>)> {
    (0..MAX_LOG_FILES)
        .map(|i| {
            let name = format!("2098-01-{:02}-120000.log", 1 + i * 2);
            let body = format!("staged by the host as boot {i}\n").into_bytes();
            (name, body)
        })
        .collect()
}

/// The log files this module's kernel wrote or was given, oldest first.
fn logs(entries: &[Entry]) -> Vec<&Entry> {
    entries.iter().filter(|e| e.name.ends_with(".log")).collect()
}

fn names(entries: &[&Entry]) -> String {
    entries.iter().map(|e| e.name.as_str()).collect::<Vec<_>>().join(", ")
}

/// The clock lines from a boot log, for a failure message that says why.
fn clock_lines(log: &str) -> String {
    let lines: Vec<&str> = log
        .lines()
        .filter(|l| {
            l.contains("clock:") || l.contains("log-file:") || l.contains("RTC") || l.contains("rtc")
        })
        .collect();
    if lines.is_empty() {
        return format!("the guest said nothing about its clock at all\n{log}");
    }
    format!("what it said:\n{}", lines.join("\n"))
}

/// A boot with the wall clock staged, returning the log volume afterwards.
///
/// Metal-sim, because that is the machine shape that gets flashed and the one
/// whose whole reason for having a log on a stick is that it has no serial
/// port. The guest is shut down before the volume is read: the claims here are
/// about the *name* and the timestamp of a file, both of which are decided when
/// the sink installs, so unlike `kernel_log_file` there is nothing to catch
/// mid-run.
fn boot_and_read(
    test_config: &Path,
    c_bins: &[(String, Vec<u8>)],
    rust_bins: &[(String, Vec<u8>)],
    image_name: &str,
    features: &'static [&'static str],
    stage: &[(String, Vec<u8>)],
) -> Result<(Vec<Entry>, String), String> {
    let image_path = super::lane::dir().join(image_name);
    let mut image = qemu::build_boot_image(test_config, c_bins, rust_bins, features);
    std::fs::write(&image_path, &image).map_err(|e| format!("write the boot image: {e}"))?;
    let (start, len) = volumes::log_extent(&image, &image_path)?;

    if !stage.is_empty() {
        volumes::stage_files(&mut image[start..start + len], stage)?;
        std::fs::write(&image_path, &image).map_err(|e| format!("rewrite the boot image: {e}"))?;
    }

    let mut qemu = QemuInstance::boot_with_options(
        test_config,
        c_bins,
        rust_bins,
        BootOptions {
            profile: qemu::Profile::Metal,
            boot_image: Some(image_path.clone()),
            kernel_features: features,
            rtc_base: Some(RTC_BASE),
            ..Default::default()
        },
    );
    let mut log = qemu.boot_log().to_string();
    serial::Serial::named("boot console", log.as_str()).must_be_clean()?;
    writeln!(qemu.stdin_mut(), "run shutdown").expect("write to QEMU stdin");
    qemu.flush_stdin();
    log.push_str(&qemu.drain_serial(Duration::from_secs(20)));
    drop(qemu);
    for bad in ["!!! PANIC !!!", "panicked at"] {
        if log.contains(bad) {
            return Err(format!("{bad:?} on the way down\n{log}"));
        }
    }

    let after = std::fs::read(&image_path).map_err(|e| format!("read the image back: {e}"))?;
    if start + len > after.len() {
        return Err(format!("the image shrank to {} bytes", after.len()));
    }
    let entries = volumes::root_entries(&after[start..start + len])?;
    let _ = std::fs::remove_file(&image_path);
    Ok((entries, log))
}

/// One file per boot, named and stamped from the wall clock, with the oldest
/// deleted once the volume is at its bound.
pub fn wall_clock_file(
    test_config: &Path,
    c_bins: &[(String, Vec<u8>)],
    rust_bins: &[(String, Vec<u8>)],
) -> Result<(), String> {
    let staged = staged_logs();
    let (entries, log) =
        boot_and_read(test_config, c_bins, rust_bins, "wall-clock-boot.img", &[], &staged)?;
    let logs = logs(&entries);

    // The bound, on the volume rather than in the guest's account of it.
    if logs.len() != MAX_LOG_FILES {
        return Err(format!(
            "the volume holds {} logs, not the {MAX_LOG_FILES} the bound allows: {}\n{}",
            logs.len(),
            names(&logs),
            clock_lines(&log)
        ));
    }

    // The oldest staged file and no other. `staged_logs` dates them two days
    // apart, so deleting by list order or by index would take a different one.
    let oldest = &staged[0].0;
    if logs.iter().any(|e| &e.name == oldest) {
        return Err(format!(
            "the oldest log {oldest} is still on the volume, so the bound was met by deleting \
             something else: {}",
            names(&logs)
        ));
    }
    for (name, _) in &staged[1..] {
        if !logs.iter().any(|e| &e.name == name) {
            return Err(format!(
                "{name} was deleted and it is not the oldest: {}\n{}",
                names(&logs),
                clock_lines(&log)
            ));
        }
    }
    if !log.contains(&format!("/log/{oldest} was deleted")) {
        return Err(format!(
            "nothing in the log names {oldest} as the file that was deleted to make room\n{}",
            clock_lines(&log)
        ));
    }

    // This boot's own file: named for the staged instant, which needs the
    // century register to come out as 2101 rather than 2001.
    let Some(mine) = logs.iter().find(|e| e.name.starts_with(RTC_BASE_DATE)) else {
        return Err(format!(
            "no log named for the day the host staged ({RTC_BASE_DATE}*): {}\n{}",
            names(&logs),
            clock_lines(&log)
        ));
    };
    let drift = mine.modified - RTC_BASE_SECS;
    if !(0..=MAX_BOOT_DRIFT_SECS).contains(&drift) {
        return Err(format!(
            "{} carries a timestamp {drift}s from the {RTC_BASE} the host set, outside \
             0..={MAX_BOOT_DRIFT_SECS}\n{}",
            mine.name,
            clock_lines(&log)
        ));
    }
    if mine.len == 0 {
        return Err(format!("{} is on the volume and empty", mine.name));
    }
    eprintln!(
        "  [clock] {} carries {} bytes, stamped {drift}s after the {RTC_BASE} the host set; \
         {} deleted for the {MAX_LOG_FILES}-log bound",
        mine.name, mine.len, oldest
    );
    Ok(())
}

/// Every way the clock can fail to answer, and the century register's absence.
///
/// One boot per state because each is a different kernel build. They share this
/// function so the four of them are one entry in the schedule and one line of
/// output.
pub fn wall_clock_refusals(
    test_config: &Path,
    c_bins: &[(String, Vec<u8>)],
    rust_bins: &[(String, Vec<u8>)],
) -> Result<(), String> {
    undated(
        test_config,
        c_bins,
        rust_bins,
        "wall-clock-dead.img",
        &["rtc-dead"],
        "its update flag never cleared",
    )?;
    undated(
        test_config,
        c_bins,
        rust_bins,
        "wall-clock-unstable.img",
        &["rtc-unstable"],
        "no two of 4 reads agreed",
    )?;
    no_century(test_config, c_bins, rust_bins)
}

/// A machine whose clock will not answer still boots, still logs, and says so
/// in the name of the file it writes.
fn undated(
    test_config: &Path,
    c_bins: &[(String, Vec<u8>)],
    rust_bins: &[(String, Vec<u8>)],
    image_name: &str,
    features: &'static [&'static str],
    because: &str,
) -> Result<(), String> {
    let (entries, log) = boot_and_read(test_config, c_bins, rust_bins, image_name, features, &[])?;
    let logs = logs(&entries);

    // The refusal, by name and with its reason. A kernel that silently took
    // some other number for the time would produce a dated file and no line.
    if !log.contains("clock: this machine will not say what time it is") || !log.contains(because) {
        return Err(format!(
            "with {features:?} the kernel never refused the clock for {because:?}\n{}",
            clock_lines(&log)
        ));
    }
    let [only] = logs.as_slice() else {
        return Err(format!("the volume holds {} logs, wanted one: {}", logs.len(), names(&logs)));
    };
    if only.name != "unknown-00.log" {
        return Err(format!(
            "with {features:?} this boot's log is {}, which claims a time the machine never gave \
             it\n{}",
            only.name,
            clock_lines(&log)
        ));
    }
    // The boot has to have *finished* — a clock that refuses must not cost the
    // machine anything else — and the file has to carry it.
    if !log.contains("Boot: complete") {
        return Err(format!("with {features:?} the boot never completed\n{log}"));
    }
    if only.len == 0 {
        return Err(format!("with {features:?} {} is on the volume and empty", only.name));
    }
    eprintln!(
        "  [clock] {features:?}: refused by name, {} carries {} bytes, boot complete",
        only.name, only.len
    );
    Ok(())
}

/// A FADT that names no century register: the year comes from two digits, and
/// the file name is what says so.
fn no_century(
    test_config: &Path,
    c_bins: &[(String, Vec<u8>)],
    rust_bins: &[(String, Vec<u8>)],
) -> Result<(), String> {
    const FEATURES: &[&str] = &["rtc-no-century"];
    let (entries, log) =
        boot_and_read(test_config, c_bins, rust_bins, "wall-clock-no-century.img", FEATURES, &[])?;
    let logs = logs(&entries);

    if !log.contains("ACPI: the FADT names no RTC century register") {
        return Err(format!("the kernel never said the FADT named no century register\n{}", clock_lines(&log)));
    }
    let [only] = logs.as_slice() else {
        return Err(format!("the volume holds {} logs, wanted one: {}", logs.len(), names(&logs)));
    };
    // 2001 and not 2101: the same registers, minus the century, are a hundred
    // years earlier. This is the assertion that fails if the kernel reads 0x32
    // whatever the FADT says, and it is the one `wall_clock_file`'s 2101 cannot
    // make on its own.
    if !only.name.starts_with("2001-06-05-0403") {
        return Err(format!(
            "with no century register this boot's log is {}, and the two-digit year makes it \
             2001-06-05\n{}",
            only.name,
            clock_lines(&log)
        ));
    }
    eprintln!("  [clock] no century register: {} , the two-digit year", only.name);
    Ok(())
}
