//! On-screen panic console.
//!
//! A dumb tail of the log ring rendered as an 8x16 text grid onto the UEFI
//! GOP framebuffer, armed before `serial::init` and painted only on fatal
//! paths. It formats nothing: `crash_report` already produced the text and
//! every ring line already carries `[kernel 12.481 cpu3 tid=7]`. A second
//! formatter for a second device would be a terminal subsystem, and it would
//! drift from the first.
//!
//! It exists because a laptop has no serial port. On such a machine the
//! screen is the only channel a kernel panic can reach, and today a panic
//! before the compositor starts is indistinguishable from a hang.
//!
//! Two entry points on the panic path, and the split between them is the
//! load-bearing decision:
//!
//!   - [`capture`] runs at the top of the panic handler, *before* the drain
//!     that `e9f3356` put there. Downstream of that drain the ring is empty,
//!     so any reader placed after it paints a blank screen on the single most
//!     common panic. It copies and consumes nothing.
//!   - [`render`] runs inside `halt_all_cpus`, *before* `panic_flush`. That
//!     ordering is only defensible because rendering consumes nothing and
//!     contains no unbounded loop, so a bug here costs the screen and never
//!     the serial report. It also means a nonce arriving on serial proves the
//!     paint already finished, which is what lets the tests skip sleeping.
//!     The early-panic branch is the one exception and inverts it: that
//!     window has no IDT, so nothing would catch a fault in here.
//!
//! A panic that *recovers* therefore captures but never paints, and
//! [`discard_capture`] drops what it captured -- otherwise the next fatal
//! path would paint a crash the machine already survived.
//!
//! The screen is smaller than the report. A 1080p panel is 67 rows and a boot
//! log is ~85 display rows before a backtrace is added, so a single paint is a
//! window over the *newest* end and everything above it is unreachable -- on a
//! machine whose input is dead there is no key to press for the rest. So the
//! text is paginated, and [`page_forever`] advances the page on a deadline
//! after the machine has halted: a phone camera left running collects the
//! whole thing. Paging happens only when the text does not fit, and the
//! `[page n/m]` footer is what tells a photograph which slice it caught.
//!
//! That the halted machine spins rather than `hlt`s is the cost, and it is
//! paid knowingly: nothing would wake it, and re-arming the LAPIC timer would
//! aim an interrupt at the scheduler from inside a panic.
//!
//! virtio-gpu is deliberately not supported. Reaching its scanout needs
//! TRANSFER_TO_HOST_2D and RESOURCE_FLUSH through `submit_and_wait`'s
//! unbounded poll behind `GPU.lock()` -- exactly the wedge family this module
//! must not join -- and it would only buy on-screen panics in the one config
//! that already has working serial. When virtio-gpu wins device selection the
//! console detaches and draws nothing.

use core::cell::UnsafeCell;
use core::sync::atomic::{AtomicBool, AtomicU32, AtomicU64, AtomicUsize, Ordering};

use toyos_abi::boot::{KernelArgs, MemoryMapEntry};

use crate::log;
use crate::mm::{self, DirectMap, align_2m};

/// 1 bpp 8x16, codepoints 0x20..=0x7E, one byte per row, bit 7 leftmost.
/// Regenerated by `cargo run -- --regen-font`; the screendump decoder in
/// `tests/common/screen.rs` reads this same file, so decoder and renderer
/// cannot drift.
static FONT: &[u8; 95 * 16] = include_bytes!("font8x16.bin");

const GLYPH_W: usize = 8;
const GLYPH_H: usize = 16;

/// Grid caps. A full exception report is ~60 lines, so 96 rows keeps the
/// whole report plus context; 320 columns covers 2560 pixels of width. Both
/// bound the stack cost of the wrap pass, which is the only array here.
const MAX_COLS: usize = 320;
const MAX_ROWS: usize = 96;

/// Half the log ring, sized by the assertion below: one screenful must never
/// exceed what was captured, or the top of a page would show text the snapshot
/// never held. Paging spends the rest — at the ~70 bytes per display row a
/// kernel log actually averages, 32 KiB is around five 96-row pages.
const SNAPSHOT_CAP: usize = 32 * 1024;
const _: () = assert!(SNAPSHOT_CAP >= MAX_ROWS * MAX_COLS);

/// How long each page stays up. Long enough to photograph, short enough that
/// a five-page report cycles inside a 15-second video.
const PAGE_HOLD_NS: u64 = 3_000_000_000;

/// The bootloader identity+high maps the first 4 GiB, and `paging::init`
/// re-maps at least that much. A framebuffer below this line is therefore
/// reachable from the first instruction of `kernel_main`; one above it is
/// only reachable after [`remap`].
const LOW_MAP_LIMIT: u64 = 4 * 1024 * 1024 * 1024;

#[derive(Clone, Copy)]
struct Fb {
    ptr: *mut u8,
    bytes: u64,
    stride_px: u32,
    width: u32,
    height: u32,
    format: u32,
}

impl Fb {
    const DETACHED: Fb = Fb {
        ptr: core::ptr::null_mut(),
        bytes: 0,
        stride_px: 0,
        width: 0,
        height: 0,
        format: 0,
    };
}

struct FbCell(UnsafeCell<Fb>);
unsafe impl Sync for FbCell {}

struct SnapshotCell(UnsafeCell<[u8; SNAPSHOT_CAP]>);
unsafe impl Sync for SnapshotCell {}

/// Seqlock over `FB`. Even means stable, odd means a publisher is inside.
/// Not a `Lock` and not even a `try_lock`: `Lock::lock` panics after 500M
/// spins, and `try_lock` disables preemption on entry while its failure path
/// and its guard's `Drop` re-enable it -- which dispatches `do_preempt` when
/// the count hits zero with `need_resched` set. The panic path must not be
/// able to reach the scheduler. A publisher that dies mid-update leaves `SEQ`
/// odd forever, which costs the screen and nothing else.
static SEQ: AtomicU32 = AtomicU32::new(0);
static FB: FbCell = FbCell(UnsafeCell::new(Fb::DETACHED));

/// Exactly one painter at a time, taken by every painter without exception.
/// Closes three modes with one instruction: two CPUs panicking at once, a
/// fault *inside* the renderer (#PF -> fatal_exception -> halt_all_cpus ->
/// re-entry -> latch -> return, so the recursion terminates at depth one),
/// and double-panic re-entry through `halt_all_cpus`.
///
/// [`render`] never releases it, which is what stops a later boot checkpoint
/// from painting over a fatal report; every fatal caller ends in `hlt`.
/// [`boot_checkpoint`] does release it, because the machine keeps running.
static PAINTING: AtomicBool = AtomicBool::new(false);

static SNAPSHOT: SnapshotCell = SnapshotCell(UnsafeCell::new([0; SNAPSHOT_CAP]));

/// Non-zero means, and only means, "a panic that has *not* been recovered
/// captured this report". [`capture`] establishes the first half and
/// [`discard_capture`] the second: without it a survived panic's report stays
/// here and a later, unrelated fatal path paints it as the cause of death.
static SNAPSHOT_LEN: AtomicUsize = AtomicUsize::new(0);

/// Scratch for the readers that peek the *live* ring: a boot checkpoint, and
/// a fatal path that never ran the panic handler. Separate from `SNAPSHOT`
/// because a checkpoint sharing it would erase a report another CPU had
/// already captured and not yet painted.
static LIVE: SnapshotCell = SnapshotCell(UnsafeCell::new([0; SNAPSHOT_CAP]));

/// Set the first time a process claims `DEVICE_FRAMEBUFFER`. Boot checkpoints
/// stop repainting once something owns the screen; a *fatal* panic ignores
/// this entirely and takes the screen back unconditionally.
static SCREEN_OWNED_BY_USERLAND: AtomicBool = AtomicBool::new(false);

/// Hand the screen over, and do not return while a checkpoint is still
/// drawing on it.
///
/// Setting the flag stops the *next* checkpoint. It does nothing about the one
/// already inside `paint`, which took `PAINTING` before the flag was set and
/// goes on writing glyphs for as long as a full-panel paint takes — and that
/// is not a short time on the machine this matters on. `paint` writes one
/// `write_volatile` per pixel into a mapping firmware left uncached, measured
/// at ~460 ms for 1920x1080 on the T14, against microseconds under QEMU where
/// the framebuffer is host RAM. So the window is invisible to every test in
/// the suite and half a second wide on the laptop.
///
/// A claimer that returns inside that window maps the scanout and starts
/// composing against a screen the kernel is still painting, and whatever the
/// checkpoint writes afterwards stays: a damage-tracked client repaints what
/// its model says changed, and the model has no idea any of this happened.
/// That leaves kernel log glyphs sitting in cells the client believes are
/// blank, for the life of the session.
///
/// Waiting is bounded by one paint and happens once per boot. Abandoning the
/// paint instead would be cheaper and wrong: it leaves the half of the screen
/// already painted on the glass, which is the same corruption.
pub fn screen_claimed_by_userland() {
    SCREEN_OWNED_BY_USERLAND.store(true, Ordering::SeqCst);
    // Bounded because a CPU that died holding the latch must not take the
    // display down with it; one paint is the honest ceiling and this is twice
    // the slowest one measured.
    let deadline = crate::clock::nanos_since_boot() + 2_000_000_000;
    while PAINTING.load(Ordering::SeqCst) {
        if crate::clock::nanos_since_boot() > deadline {
            log!("panic console: claim waited 2s for a checkpoint that never finished");
            return;
        }
        core::hint::spin_loop();
    }
}

/// The descriptor [`arm`] validated, held so [`remap`] and [`rearm`] can
/// re-publish it without re-deriving anything. A null pointer here means
/// there is no usable GOP framebuffer at all, and no later call can invent
/// one. Written only during single-threaded boot.
static PENDING: FbCell = FbCell(UnsafeCell::new(Fb::DETACHED));
static RAW_PHYS: AtomicU64 = AtomicU64::new(0);
static RAW_SIZE: AtomicU64 = AtomicU64::new(0);

/// Boot-time and `set_resolution`-window only, so the load-then-store of `SEQ`
/// needs no CAS: publishers never race each other, only readers.
fn publish(fb: Fb) {
    let seq = SEQ.load(Ordering::Relaxed);
    SEQ.store(seq.wrapping_add(1), Ordering::Relaxed);
    // Both fences are the seqlock, and neither is decoration. A release *RMW*
    // on the odd transition would order what precedes it, not what follows,
    // leaving the compiler free to hoist the descriptor store above the odd
    // marker -- at which point a reader that saw an even sequence on both
    // sides could still have read a half-written descriptor.
    core::sync::atomic::fence(Ordering::Release);
    unsafe { *FB.0.get() = fb };
    SEQ.store(seq.wrapping_add(2), Ordering::Release);
}

/// Stop painting until the next [`rearm`]. For a window in which the
/// framebuffer may be freed and reallocated under us: the worst case becomes
/// "no console", never a write into whatever took its place.
pub fn detach() {
    publish(Fb::DETACHED);
}

/// Re-publish the armed descriptor after such a window.
pub fn rearm() {
    let fb = unsafe { *PENDING.0.get() };
    if validate(&fb) {
        publish(fb);
    }
}

/// Give up the display permanently. Called when virtio-gpu wins device
/// selection: its scanout is unreachable from the panic path, and clearing
/// PENDING is what stops a later `rearm` from resurrecting the firmware
/// framebuffer nobody is scanning out any more.
pub fn disable() {
    unsafe { *PENDING.0.get() = Fb::DETACHED };
    RAW_PHYS.store(0, Ordering::Relaxed);
    detach();
}

/// Torn means unavailable, never a wild pointer -- and that has to hold on
/// the ordering, not on the values. Today only two descriptors are ever
/// published, one `validate`d and one all-zero, so every torn mixture is
/// caught downstream by the null check below, by `bytes == 0` collapsing
/// `row_base`/`put_pixel` to no-ops, or by `width == 0` giving `cols == 0`.
/// The moment a *second valid* descriptor exists -- which `detach`/`rearm`
/// anticipate -- that argument is gone and only the fences are left.
fn snapshot() -> Option<Fb> {
    for _ in 0..4 {
        let before = SEQ.load(Ordering::Acquire);
        if before & 1 != 0 {
            continue;
        }
        let fb = unsafe { *FB.0.get() };
        core::sync::atomic::fence(Ordering::Acquire);
        if SEQ.load(Ordering::Relaxed) == before {
            return (!fb.ptr.is_null()).then_some(fb);
        }
    }
    None
}

/// Reject a descriptor that could turn a panic into a wild write. Geometry
/// bounds keep every later product inside `u64`, and the kernel-address check
/// keeps the base inside the direct map.
fn validate(fb: &Fb) -> bool {
    if fb.ptr.is_null() || !mm::is_kernel_addr(fb.ptr as u64) {
        return false;
    }
    if !(1..=16384).contains(&fb.width) || !(1..=16384).contains(&fb.height) {
        return false;
    }
    if fb.stride_px < fb.width || fb.stride_px > 65536 {
        return false;
    }
    let needed = (fb.stride_px as u64)
        .checked_mul(fb.height as u64)
        .and_then(|v| v.checked_mul(4));
    matches!(needed, Some(n) if fb.bytes >= n)
}

/// Whether the UEFI memory map hands `phys` to the PMM as free RAM.
///
/// A firmware GOP that is a shim over memory the kernel later re-owns would
/// make the panic path a write into the heap. `pmm::is_usable` counts
/// `BootServicesData` and `LoaderData` as free, so this is not hypothetical
/// on firmware that allocates its scanout from boot services.
fn framebuffer_is_reclaimed_ram(maps: &[MemoryMapEntry], phys: u64) -> Option<u32> {
    let entry = maps.iter().find(|e| phys >= e.start && phys < e.end)?;
    mm::pmm::is_usable_type(entry.uefi_type).then_some(entry.uefi_type)
}

/// Arm the console from `KernelArgs`, before `serial::init`.
///
/// Everything from here to `mm::init` -- including `serial::init`'s own UART
/// probe -- is covered, because the bootloader's identity+high map already
/// reaches a sub-4 GiB framebuffer and no kernel mapping exists yet.
pub fn arm(args: &KernelArgs, maps: &[MemoryMapEntry]) {
    if args.gop_framebuffer == 0 {
        return;
    }

    if let Some(uefi_type) = framebuffer_is_reclaimed_ram(maps, args.gop_framebuffer) {
        log!(
            "panic console: disarmed, framebuffer at {:#x} is UEFI type {} (PMM-owned RAM)",
            args.gop_framebuffer,
            uefi_type
        );
        return;
    }

    let fb = Fb {
        ptr: DirectMap::from_phys(args.gop_framebuffer).as_mut_ptr::<u8>(),
        bytes: args.gop_framebuffer_size,
        stride_px: args.gop_stride,
        width: args.gop_width,
        height: args.gop_height,
        format: args.gop_pixel_format,
    };
    if !validate(&fb) {
        log!(
            "panic console: disarmed, bad descriptor {}x{} stride={} size={:#x}",
            args.gop_width, args.gop_height, args.gop_stride, args.gop_framebuffer_size
        );
        return;
    }

    unsafe { *PENDING.0.get() = fb };
    RAW_PHYS.store(args.gop_framebuffer, Ordering::Relaxed);
    RAW_SIZE.store(args.gop_framebuffer_size, Ordering::Relaxed);

    match args.gop_framebuffer.checked_add(args.gop_framebuffer_size) {
        Some(end) if end <= LOW_MAP_LIMIT => {
            publish(fb);
            log!(
                "panic console: armed {}x{} stride={} format={} at {:#x}",
                fb.width, fb.height, fb.stride_px, fb.format, args.gop_framebuffer
            );
        }
        _ => log!(
            "panic console: framebuffer at {:#x} is above the boot map, armed after mm::init",
            args.gop_framebuffer
        ),
    }
}

/// Re-establish the mapping after `mm::init` replaces the bootloader's page
/// tables, and arm a framebuffer that sits above the boot map's 4 GiB reach.
pub fn remap() {
    let phys = RAW_PHYS.load(Ordering::Relaxed);
    if phys == 0 {
        return;
    }
    let size = RAW_SIZE.load(Ordering::Relaxed);
    mm::paging::kernel()
        .lock()
        .as_mut()
        .unwrap()
        .map_mmio(phys, align_2m(size as usize) as u64);
    rearm();
}

/// Copy the newest ring bytes into the console's static scratch.
///
/// Called at the top of the panic handler, before `panic_flush` drains the
/// ring. No pixels, no lock, no mutation -- one memcpy on a path that is
/// about to halt. Skipped entirely when no framebuffer is armed, which is
/// every headless boot, so a panic storm on a server pays nothing.
///
/// **Its original reason is gone, and it was kept anyway.** It existed because
/// `panic_flush` drained the ring out from under the renderer, so a reader
/// placed after the flush painted a blank screen. Since the ring retains what
/// serial has collected (see `log_ring`), a drain erases nothing and
/// [`live_tail`] after the flush returns the same text. Measured, not assumed:
/// with the body of this function replaced by `return`, `screen_late_panic`
/// still passes -- and `main.rs` used to claim that test was "the one test
/// that fails if the capture stops happening". Nothing in the tree now
/// distinguishes capture-present from capture-absent.
///
/// What remains is narrower than the original reason and is why it is still
/// here: this freezes the report at the instant of the panic, while
/// `live_tail` re-reads a ring that siblings are still writing to. The halt
/// IPI is maskable, so a CPU with IF=0 keeps running until it re-enables, and
/// one spinning in a `log!` loop can push 32 KiB through the ring between the
/// panic and the paint -- which would push the report off the tail. That is
/// unlikely, unstaged, and not what the code was written for.
///
/// So: delete it if you can stage that race and show it does not matter, or if
/// you decide a diluted tail is an acceptable worst case. Do not delete it on
/// the grounds that the tests still pass, because they will.
pub fn capture() {
    if snapshot().is_none() {
        return;
    }
    let buf = unsafe { &mut *SNAPSHOT.0.get() };
    let n = unsafe { crate::drivers::log_ring::peek_tail(buf) };
    SNAPSHOT_LEN.store(n, Ordering::Relaxed);
}

/// Drop the captured report: this panic was survived, so it is no longer
/// anyone's cause of death. Called on the recovery branch, which is the only
/// exit from the panic handler that does not paint.
pub fn discard_capture() {
    SNAPSHOT_LEN.store(0, Ordering::Relaxed);
}

/// The tail of the live ring, for callers with nothing captured. Mutates
/// nothing in the ring, so a later `panic_flush` reports byte-identically.
fn live_tail() -> &'static [u8] {
    let base = LIVE.0.get().cast::<u8>();
    let n = unsafe {
        crate::drivers::log_ring::peek_tail(core::slice::from_raw_parts_mut(base, SNAPSHOT_CAP))
    };
    unsafe { core::slice::from_raw_parts(base, n) }
}

// DESIGN RULE: render and everything it calls acquires NO synchronization
// primitive -- not `Lock::lock`, not `Lock::try_lock`, not `RingGuard`, not
// `BackendGuard`. try_lock is banned too: it disables preemption on entry and
// its failure path re-enables it, which can dispatch the scheduler. No
// allocation, no `use alloc::`, no `&dyn`, no unwrap/expect/[]. Checked or
// saturating arithmetic only -- overflow-checks are on, so an overflow here is
// a panic inside a panic. Every framebuffer write is clamped to the published
// byte count. Stack budget is 256 bytes plus the one wrap array; the double
// fault path runs on IST1, which is 4096 bytes and already partly consumed by
// kernel_backtrace_safe.

/// What a fatal path paints: the captured report, or -- for a path that
/// reached `halt_all_cpus` without the panic handler, a fatal exception or the
/// scheduler abort -- the live ring, which still holds it.
///
/// Idempotent for the captured case, which is the one [`page_forever`] walks
/// repeatedly: `SNAPSHOT` is written once and never again. The live branch
/// re-peeks, and tolerates a sibling still logging for the same reason
/// [`live_tail`] always did.
fn fatal_text() -> &'static [u8] {
    let captured = SNAPSHOT_LEN.load(Ordering::Relaxed).min(SNAPSHOT_CAP);
    if captured > 0 {
        let base = SNAPSHOT.0.get().cast::<u8>();
        unsafe { core::slice::from_raw_parts(base, captured) }
    } else {
        live_tail()
    }
}

/// Paint the newest page of the captured report. Fatal paths only. Returns
/// whether this call is the one that took the screen, which is what entitles
/// its caller -- and only its caller -- to go on to [`page_forever`].
pub fn render() -> bool {
    if PAINTING.swap(true, Ordering::SeqCst) {
        return false;
    }
    paint(Fill::Fatal, fatal_text(), Page::Last);
    true
}

/// Cycle the report across the screen until the machine is switched off.
///
/// Reached only from `halt_all_cpus`, only after `panic_flush`, and only on
/// the CPU whose [`render`] took `PAINTING` -- so the serial report is already
/// out and nothing here can cost it, and no second CPU can be painting
/// alongside. Returns without looping when there is nothing to page: a single
/// page, no framebuffer, or a panic early enough that the TSC is uncalibrated
/// and there is no deadline to wait on.
///
/// The panic handler's other two exits call [`render`] and not this, and the
/// reasons are different. The early-boot branch is before `clock::init`, so
/// the deadline does not exist yet -- and its report is four rows. The reentry
/// branch is a panic inside the panic path: it has to stop, not settle into a
/// loop that would keep a CPU in the code that just faulted.
pub fn page_forever() {
    if !crate::clock::calibrated() {
        return;
    }
    let text = fatal_text();
    let Some(fb) = snapshot() else { return };
    let Some((cols, grid_rows)) = geometry(&fb) else { return };
    let (_, pages, _) = pagination(text, cols, grid_rows);
    if pages < 2 {
        return;
    }
    let mut page = 0;
    loop {
        hold(PAGE_HOLD_NS);
        paint(Fill::Fatal, text, Page::Nth(page));
        page += 1;
        if page == pages {
            page = 0;
        }
    }
}

/// Busy-wait `nanos`. `nanos_since_boot` is an `rdtsc` and two relaxed loads --
/// no lock, no MMIO, nothing the panic path is forbidden to touch.
fn hold(nanos: u64) {
    let target = crate::clock::nanos_since_boot().saturating_add(nanos);
    while crate::clock::nanos_since_boot() < target {
        core::hint::spin_loop();
    }
}

/// Repaint at a boot phase boundary, so a machine that wedges later still
/// shows how far it got. Converts "black screen" into "NVMe came up, xHCI
/// did not" for free, which is the only coverage there is for a hang that
/// never panics.
pub fn boot_checkpoint() {
    if SCREEN_OWNED_BY_USERLAND.load(Ordering::Relaxed) {
        return;
    }
    // The same latch, taken the same way: an AP that misses `boot_aps`' 100 ms
    // deadline can panic while the BSP is inside a checkpoint, and a plain
    // load here let the checkpoint paint over its report. Losing the race
    // costs a checkpoint or one fatal repaint; serial reports either way.
    if PAINTING.swap(true, Ordering::SeqCst) {
        return;
    }
    paint(Fill::Boot, live_tail(), Page::Last);
    PAINTING.store(false, Ordering::SeqCst);
}

/// Which slice of the text a paint shows.
#[derive(Clone, Copy)]
enum Page {
    /// The newest screenful, whatever the page grid says. A report must fill
    /// the screen it is painted on; a page-aligned last page would leave the
    /// bottom two thirds blank whenever the row count divides badly.
    Last,
    Nth(usize),
}

/// The fill colour carries "halted" versus "still booting" at zero cost, and
/// the fill itself is the proof the console ran *this* boot rather than a
/// stale frame surviving.
#[derive(Clone, Copy)]
enum Fill {
    Fatal,
    Boot,
}

/// The text grid a framebuffer offers, or `None` when it offers none.
fn geometry(fb: &Fb) -> Option<(usize, usize)> {
    let cols = (fb.width as usize / GLYPH_W).min(MAX_COLS);
    let rows = (fb.height as usize / GLYPH_H).min(MAX_ROWS);
    (cols != 0 && rows != 0).then_some((cols, rows))
}

/// Display rows `text` occupies, wrapping at `cols`.
///
/// Wrap, do not clip: a backtrace line carrying a demangled Rust symbol
/// routinely exceeds 160 columns and the symbol is the single most valuable
/// token on the screen.
fn count_rows(text: &[u8], cols: usize) -> usize {
    let mut rows = 1;
    let mut col = 0usize;
    let mut i = 0usize;
    while i < text.len() {
        let newline = text[i] == b'\n';
        i += 1;
        col += 1;
        if newline || col == cols {
            rows += 1;
            col = 0;
        }
    }
    rows
}

/// Total display rows, pages, and rows per page.
///
/// A text that fits gets the whole grid and one page, so a screen that never
/// needed paging is byte-identical to what it was before paging existed. One
/// that does not fit gives the bottom row to the `[page n/m]` footer, because
/// a paging console whose page nobody can identify is a slideshow.
fn pagination(text: &[u8], cols: usize, grid_rows: usize) -> (usize, usize, usize) {
    let total = count_rows(text, cols);
    if total <= grid_rows || grid_rows < 2 {
        return (total, 1, grid_rows);
    }
    let per = grid_rows - 1;
    (total, total.div_ceil(per), per)
}

/// Byte offsets of display rows `first ..`, one per slot in `out`. Rows past
/// the end get `text.len()`, which draws nothing.
fn row_offsets(text: &[u8], cols: usize, first: usize, out: &mut [u32]) {
    let len = text.len();
    for slot in out.iter_mut() {
        *slot = len as u32;
    }
    if first == 0 {
        if let Some(slot) = out.first_mut() {
            *slot = 0;
        }
    }
    let mut row = 0usize;
    let mut col = 0usize;
    let mut i = 0usize;
    while i < len {
        let newline = text[i] == b'\n';
        i += 1;
        col += 1;
        if newline || col == cols {
            row += 1;
            col = 0;
            if row >= first {
                let slot = row - first;
                if slot >= out.len() {
                    return;
                }
                out[slot] = i as u32;
            }
        }
    }
}

fn paint(fill: Fill, text: &[u8], page: Page) {
    let Some(fb) = snapshot() else { return };
    if !mapped(&fb) {
        return;
    }
    let Some((cols, grid_rows)) = geometry(&fb) else { return };
    let len = text.len();
    let (total, pages, per) = pagination(text, cols, grid_rows);
    // `Last` is the newest `per` rows rather than page `pages - 1`, so the two
    // agree on a text that divides evenly and `Last` still fills the screen
    // when it does not. The overlap that buys is a few repeated rows at the
    // end of a cycle, which is the cheap direction to be wrong in -- but it
    // does mean the footer's number cannot be derived from `first`.
    let newest = total.saturating_sub(per);
    let (first, shown) = match page {
        Page::Last => (newest, pages),
        Page::Nth(n) => (n.saturating_mul(per).min(newest), (n + 1).min(pages)),
    };

    fill_screen(
        &fb,
        match fill {
            Fill::Fatal => rgb(&fb, 0x60, 0x00, 0x00),
            Fill::Boot => 0,
        },
    );

    // The only array in this module and the one place the stack budget
    // stretches; `per <= MAX_ROWS` is what keeps the slice in bounds.
    let mut row_start = [0u32; MAX_ROWS];
    let draw = per.min(total - first).min(MAX_ROWS);
    row_offsets(text, cols, first, &mut row_start[..draw]);

    let white = rgb(&fb, 0xFF, 0xFF, 0xFF);
    let alert = rgb(&fb, 0xFF, 0x50, 0x50);

    for r in 0..draw {
        let start = row_start[r] as usize;
        let color = if has_alert(text, start, len, cols) { alert } else { white };
        let mut off = start;
        let mut c = 0;
        while c < cols && off < len {
            if text[off] == b'\n' {
                break;
            }
            draw_glyph(&fb, c, r, text[off], color);
            off += 1;
            c += 1;
        }
    }

    if pages > 1 {
        draw_footer(&fb, cols, grid_rows - 1, shown, pages, white);
    }

    // The scanout is mapped write-back over a region firmware typically marks
    // WC or UC. QEMU does not care; a real panel does, and "the text is in L2
    // and never reached the screen" is a bug that would only ever appear on
    // metal -- so it is not optional for a boot checkpoint either, even though
    // that path leaves the machine running and pays a full cache-hierarchy
    // flush per phase boundary for it. Six on a GOP boot, none on any other.
    unsafe { core::arch::asm!("wbinvd", options(nostack, preserves_flags)) };
}

/// `[page 2/4]` on the bottom row, and the module's only formatting.
///
/// It is not decoration. The pager advances on a timer with no key to press,
/// so the artifact is a photograph of one page out of several: without this a
/// reader cannot tell which slice they caught, whether the head is above them,
/// or whether the screen is cycling at all rather than wedged.
fn draw_footer(fb: &Fb, cols: usize, row: usize, page: usize, pages: usize, color: u32) {
    let mut buf = [0u8; 24];
    let mut n = 0;
    for &b in b"[page " {
        buf[n] = b;
        n += 1;
    }
    n += write_num(&mut buf[n..], page);
    buf[n] = b'/';
    n += 1;
    n += write_num(&mut buf[n..], pages);
    buf[n] = b']';
    n += 1;
    for c in 0..n.min(cols) {
        draw_glyph(fb, c, row, buf[c], color);
    }
}

/// Decimal `v` into the front of `out`, returning the bytes written. `out` is
/// always the tail of a 24-byte buffer holding at most two numbers, and a page
/// count is bounded by `SNAPSHOT_CAP`, so ten digits of room is nine spare.
fn write_num(out: &mut [u8], v: usize) -> usize {
    let mut digits = [0u8; 20];
    let mut n = 0;
    let mut v = v;
    loop {
        digits[n] = b'0' + (v % 10) as u8;
        n += 1;
        v /= 10;
        if v == 0 || n == digits.len() {
            break;
        }
    }
    for i in 0..n.min(out.len()) {
        out[i] = digits[n - 1 - i];
    }
    n.min(out.len())
}

/// Every fatal marker the kernel emits already matches this: `!!! PANIC !!!`,
/// `!!! DOUBLE PANIC !!!`, `!!! FAULT ... RECURSIVE`, the reentry line. Three
/// bytes per column is what makes a phone photo of 50 lines of text usable.
fn has_alert(text: &[u8], start: usize, len: usize, cols: usize) -> bool {
    let mut run = 0;
    let mut off = start;
    let mut c = 0;
    while c < cols && off < len {
        if text[off] == b'\n' {
            break;
        }
        run = if text[off] == b'!' { run + 1 } else { 0 };
        if run == 3 {
            return true;
        }
        off += 1;
        c += 1;
    }
    false
}

/// Whether the first and last framebuffer pages resolve in the *current* CR3.
///
/// Not `kernel_cr3()`: a panic in syscall context runs on a user address
/// space, which copies the kernel's top-half PML4 entries at creation. Shared
/// page directories propagate later mappings, but this proves it rather than
/// assuming it -- and it is what turns "the page tables are why we panicked"
/// into no console instead of a fault inside the panic handler.
fn mapped(fb: &Fb) -> bool {
    let base = fb.ptr as u64;
    let Some(last) = base.checked_add(fb.bytes.saturating_sub(1)) else {
        return false;
    };
    mm::paging::present_in_current_cr3(base) && mm::paging::present_in_current_cr3(last)
}

/// `pixel_format` is 0 for RGB and 1 for BGR (`bootloader/src/main.rs`). As a
/// little-endian u32 that is the byte order of the low three bytes.
fn rgb(fb: &Fb, r: u32, g: u32, b: u32) -> u32 {
    if fb.format == 0 {
        r | (g << 8) | (b << 16)
    } else {
        b | (g << 8) | (r << 16)
    }
}

#[inline]
fn put_pixel(fb: &Fb, x: usize, y: usize, color: u32) {
    let Some(row) = (y as u64).checked_mul(fb.stride_px as u64) else { return };
    let Some(idx) = row.checked_add(x as u64).and_then(|v| v.checked_mul(4)) else { return };
    if idx.saturating_add(4) > fb.bytes {
        return;
    }
    unsafe { core::ptr::write_volatile(fb.ptr.add(idx as usize) as *mut u32, color) };
}

/// Base pointer for a row, given that `len` pixels will be written from it.
/// `None` means the row does not fit the published byte count, which for a
/// left-to-right top-to-bottom walk means neither does any later row.
fn row_base(fb: &Fb, y: usize, len: usize) -> Option<*mut u32> {
    let start = (y as u64).checked_mul(fb.stride_px as u64)?.checked_mul(4)?;
    let end = start.checked_add((len as u64).checked_mul(4)?)?;
    (end <= fb.bytes).then(|| unsafe { fb.ptr.add(start as usize) as *mut u32 })
}

/// Erases whatever the compositor left behind, so nothing on screen is
/// ambiguous about which boot it came from.
///
/// Proves the clamp once per row rather than once per pixel: a boot
/// checkpoint repaints six times and a 2048x2048 panel is 4.2M pixels, so
/// per-pixel checked arithmetic here is the difference between a repaint
/// nobody notices and one that doubles boot time.
/// Paint the whole panel a colour no glyph contains, over whatever is there.
///
/// The actuator for "something drew on the glass behind the console's back".
/// Nothing else in reach can stage it: `DEVICE_FRAMEBUFFER` is claimed
/// exclusively so no second process can map the scanout, `boot_checkpoint`
/// returns the moment userland owns the screen, and the one painter that
/// ignores that claim — `render` — halts the machine on its way out, which
/// leaves nobody to type the command under test.
///
/// It covers the strip below the last glyph row too, which is the half of this
/// a console composing cell by cell can never reach on its own.
#[cfg(feature = "test-screen-graffiti")]
pub fn graffiti() {
    let Some(fb) = snapshot() else { return };
    if !mapped(&fb) {
        return;
    }
    log!("SYS_DEBUG: painting over the screen a userland process owns");
    fill_screen(&fb, rgb(&fb, 0x00, 0xC0, 0x00));
}

fn fill_screen(fb: &Fb, color: u32) {
    let width = fb.width as usize;
    for y in 0..fb.height as usize {
        let Some(row) = row_base(fb, y, width) else { return };
        for x in 0..width {
            unsafe { core::ptr::write_volatile(row.add(x), color) };
        }
    }
}

fn draw_glyph(fb: &Fb, cell_x: usize, cell_y: usize, byte: u8, color: u32) {
    let ch = match byte {
        b'\t' => b' ',
        0x20..=0x7E => byte,
        _ => b'.',
    };
    let base = (ch - 0x20) as usize * GLYPH_H;
    let ox = cell_x * GLYPH_W;
    let oy = cell_y * GLYPH_H;
    for (row, &bits) in FONT[base..base + GLYPH_H].iter().enumerate() {
        if bits == 0 {
            continue;
        }
        for bit in 0..GLYPH_W {
            if bits & (0x80 >> bit) != 0 {
                put_pixel(fb, ox + bit, oy + row, color);
            }
        }
    }
}
