//! On-screen panic console.
//!
//! A dumb tail of the log ring rendered as an 8x16 text grid onto the UEFI
//! GOP framebuffer, armed before `serial::init` and painted only on fatal
//! paths. It formats nothing: `crash_report` already produced the text and
//! every ring line already carries `[kernel 12.481 cpu3 tid=7]`. A second
//! formatter for a second device would be a terminal subsystem, and it would
//! drift from the first.
//!
//! It exists because a laptop has no serial port. On such a machine the
//! screen is the only channel a kernel panic can reach, and today a panic
//! before the compositor starts is indistinguishable from a hang.
//!
//! Two entry points on the panic path, and the split between them is the
//! load-bearing decision:
//!
//!   - [`capture`] runs at the top of the panic handler, *before* the drain
//!     that `e9f3356` put there. Downstream of that drain the ring is empty,
//!     so any reader placed after it paints a blank screen on the single most
//!     common panic. It copies and consumes nothing.
//!   - [`render`] runs inside `halt_all_cpus`, *before* `panic_flush`. That
//!     ordering is only defensible because rendering consumes nothing and
//!     contains no unbounded loop, so a bug here costs the screen and never
//!     the serial report. It also means a nonce arriving on serial proves the
//!     paint already finished, which is what lets the tests skip sleeping.
//!
//! A panic that *recovers* therefore captures but never paints: recovery
//! diverges before `halt_all_cpus`, so "a live desktop is never clobbered by
//! a survivable fault" falls out of the call sites with no flag to get wrong.
//!
//! virtio-gpu is deliberately not supported. Reaching its scanout needs
//! TRANSFER_TO_HOST_2D and RESOURCE_FLUSH through `submit_and_wait`'s
//! unbounded poll behind `GPU.lock()` -- exactly the wedge family this module
//! must not join -- and it would only buy on-screen panics in the one config
//! that already has working serial. When virtio-gpu wins device selection the
//! console detaches and draws nothing.

use core::cell::UnsafeCell;
use core::sync::atomic::{AtomicBool, AtomicU32, AtomicU64, AtomicUsize, Ordering};

use toyos_abi::boot::{KernelArgs, MemoryMapEntry};

use crate::log;
use crate::mm::{self, DirectMap, align_2m};

/// 1 bpp 8x16, codepoints 0x20..=0x7E, one byte per row, bit 7 leftmost.
/// Regenerated by `cargo run -- --regen-font`; the screendump decoder in
/// `tests/common/screen.rs` reads this same file, so decoder and renderer
/// cannot drift.
static FONT: &[u8; 95 * 16] = include_bytes!("font8x16.bin");

const GLYPH_W: usize = 8;
const GLYPH_H: usize = 16;

/// Grid caps. A full exception report is ~60 lines, so 96 rows keeps the
/// whole report plus context; 320 columns covers 2560 pixels of width. Both
/// bound the stack cost of the wrap pass, which is the only array here.
const MAX_COLS: usize = 320;
const MAX_ROWS: usize = 96;

/// Half the log ring, sized by the assertion below: the on-screen budget must
/// never exceed what was captured, or the top of the screen would show text
/// the snapshot never held.
const SNAPSHOT_CAP: usize = 32 * 1024;
const _: () = assert!(SNAPSHOT_CAP >= MAX_ROWS * MAX_COLS);

/// The bootloader identity+high maps the first 4 GiB, and `paging::init`
/// re-maps at least that much. A framebuffer below this line is therefore
/// reachable from the first instruction of `kernel_main`; one above it is
/// only reachable after [`remap`].
const LOW_MAP_LIMIT: u64 = 4 * 1024 * 1024 * 1024;

#[derive(Clone, Copy)]
struct Fb {
    ptr: *mut u8,
    bytes: u64,
    stride_px: u32,
    width: u32,
    height: u32,
    format: u32,
}

impl Fb {
    const DETACHED: Fb = Fb {
        ptr: core::ptr::null_mut(),
        bytes: 0,
        stride_px: 0,
        width: 0,
        height: 0,
        format: 0,
    };
}

struct FbCell(UnsafeCell<Fb>);
unsafe impl Sync for FbCell {}

struct SnapshotCell(UnsafeCell<[u8; SNAPSHOT_CAP]>);
unsafe impl Sync for SnapshotCell {}

/// Seqlock over `FB`. Even means stable, odd means a publisher is inside.
/// Not a `Lock` and not even a `try_lock`: `Lock::lock` panics after 500M
/// spins, and `try_lock` disables preemption on entry while its failure path
/// and its guard's `Drop` re-enable it -- which dispatches `do_preempt` when
/// the count hits zero with `need_resched` set. The panic path must not be
/// able to reach the scheduler. A publisher that dies mid-update leaves `SEQ`
/// odd forever, which costs the screen and nothing else.
static SEQ: AtomicU32 = AtomicU32::new(0);
static FB: FbCell = FbCell(UnsafeCell::new(Fb::DETACHED));

/// Set once, never cleared. Closes three modes with one instruction: two CPUs
/// panicking at once (exactly one painter, ever), a fault *inside* the
/// renderer (#PF -> fatal_exception -> halt_all_cpus -> re-entry -> latch ->
/// return, so the recursion terminates at depth one), and double-panic
/// re-entry through `halt_all_cpus`. Never cleared is correct: every caller
/// ends in `hlt`.
static PAINTING: AtomicBool = AtomicBool::new(false);

static SNAPSHOT: SnapshotCell = SnapshotCell(UnsafeCell::new([0; SNAPSHOT_CAP]));
static SNAPSHOT_LEN: AtomicUsize = AtomicUsize::new(0);

/// Set the first time a process claims `DEVICE_FRAMEBUFFER`. Boot checkpoints
/// stop repainting once something owns the screen; a *fatal* panic ignores
/// this entirely and takes the screen back unconditionally.
static SCREEN_OWNED_BY_USERLAND: AtomicBool = AtomicBool::new(false);

pub fn screen_claimed_by_userland() {
    SCREEN_OWNED_BY_USERLAND.store(true, Ordering::Relaxed);
}

/// The descriptor [`arm`] validated, held so [`remap`] and [`rearm`] can
/// re-publish it without re-deriving anything. A null pointer here means
/// there is no usable GOP framebuffer at all, and no later call can invent
/// one. Written only during single-threaded boot.
static PENDING: FbCell = FbCell(UnsafeCell::new(Fb::DETACHED));
static RAW_PHYS: AtomicU64 = AtomicU64::new(0);
static RAW_SIZE: AtomicU64 = AtomicU64::new(0);

fn publish(fb: Fb) {
    SEQ.fetch_add(1, Ordering::Release);
    unsafe { *FB.0.get() = fb };
    SEQ.fetch_add(1, Ordering::Release);
}

/// Stop painting until the next [`rearm`]. For a window in which the
/// framebuffer may be freed and reallocated under us: the worst case becomes
/// "no console", never a write into whatever took its place.
pub fn detach() {
    publish(Fb::DETACHED);
}

/// Re-publish the armed descriptor after such a window.
pub fn rearm() {
    let fb = unsafe { *PENDING.0.get() };
    if validate(&fb) {
        publish(fb);
    }
}

/// Give up the display permanently. Called when virtio-gpu wins device
/// selection: its scanout is unreachable from the panic path, and clearing
/// PENDING is what stops a later `rearm` from resurrecting the firmware
/// framebuffer nobody is scanning out any more.
pub fn disable() {
    unsafe { *PENDING.0.get() = Fb::DETACHED };
    RAW_PHYS.store(0, Ordering::Relaxed);
    detach();
}

fn snapshot() -> Option<Fb> {
    for _ in 0..4 {
        let before = SEQ.load(Ordering::Acquire);
        if before & 1 != 0 {
            continue;
        }
        let fb = unsafe { *FB.0.get() };
        if SEQ.load(Ordering::Acquire) == before {
            return (!fb.ptr.is_null()).then_some(fb);
        }
    }
    None
}

/// Reject a descriptor that could turn a panic into a wild write. Geometry
/// bounds keep every later product inside `u64`, and the kernel-address check
/// keeps the base inside the direct map.
fn validate(fb: &Fb) -> bool {
    if fb.ptr.is_null() || !mm::is_kernel_addr(fb.ptr as u64) {
        return false;
    }
    if !(1..=16384).contains(&fb.width) || !(1..=16384).contains(&fb.height) {
        return false;
    }
    if fb.stride_px < fb.width || fb.stride_px > 65536 {
        return false;
    }
    let needed = (fb.stride_px as u64)
        .checked_mul(fb.height as u64)
        .and_then(|v| v.checked_mul(4));
    matches!(needed, Some(n) if fb.bytes >= n)
}

/// Whether the UEFI memory map hands `phys` to the PMM as free RAM.
///
/// A firmware GOP that is a shim over memory the kernel later re-owns would
/// make the panic path a write into the heap. `pmm::is_usable` counts
/// `BootServicesData` and `LoaderData` as free, so this is not hypothetical
/// on firmware that allocates its scanout from boot services.
fn framebuffer_is_reclaimed_ram(maps: &[MemoryMapEntry], phys: u64) -> Option<u32> {
    let entry = maps.iter().find(|e| phys >= e.start && phys < e.end)?;
    mm::pmm::is_usable_type(entry.uefi_type).then_some(entry.uefi_type)
}

/// Arm the console from `KernelArgs`, before `serial::init`.
///
/// Everything from here to `mm::init` -- including `serial::init`'s own UART
/// probe -- is covered, because the bootloader's identity+high map already
/// reaches a sub-4 GiB framebuffer and no kernel mapping exists yet.
pub fn arm(args: &KernelArgs, maps: &[MemoryMapEntry]) {
    if args.gop_framebuffer == 0 {
        return;
    }

    if let Some(uefi_type) = framebuffer_is_reclaimed_ram(maps, args.gop_framebuffer) {
        log!(
            "panic console: disarmed, framebuffer at {:#x} is UEFI type {} (PMM-owned RAM)",
            args.gop_framebuffer,
            uefi_type
        );
        return;
    }

    let fb = Fb {
        ptr: DirectMap::from_phys(args.gop_framebuffer).as_mut_ptr::<u8>(),
        bytes: args.gop_framebuffer_size,
        stride_px: args.gop_stride,
        width: args.gop_width,
        height: args.gop_height,
        format: args.gop_pixel_format,
    };
    if !validate(&fb) {
        log!(
            "panic console: disarmed, bad descriptor {}x{} stride={} size={:#x}",
            args.gop_width, args.gop_height, args.gop_stride, args.gop_framebuffer_size
        );
        return;
    }

    unsafe { *PENDING.0.get() = fb };
    RAW_PHYS.store(args.gop_framebuffer, Ordering::Relaxed);
    RAW_SIZE.store(args.gop_framebuffer_size, Ordering::Relaxed);

    match args.gop_framebuffer.checked_add(args.gop_framebuffer_size) {
        Some(end) if end <= LOW_MAP_LIMIT => {
            publish(fb);
            log!(
                "panic console: armed {}x{} stride={} format={} at {:#x}",
                fb.width, fb.height, fb.stride_px, fb.format, args.gop_framebuffer
            );
        }
        _ => log!(
            "panic console: framebuffer at {:#x} is above the boot map, armed after mm::init",
            args.gop_framebuffer
        ),
    }
}

/// Re-establish the mapping after `mm::init` replaces the bootloader's page
/// tables, and arm a framebuffer that sits above the boot map's 4 GiB reach.
pub fn remap() {
    let phys = RAW_PHYS.load(Ordering::Relaxed);
    if phys == 0 {
        return;
    }
    let size = RAW_SIZE.load(Ordering::Relaxed);
    mm::paging::kernel()
        .lock()
        .as_mut()
        .unwrap()
        .map_mmio(phys, align_2m(size as usize) as u64);
    rearm();
}

/// Copy the newest ring bytes into the console's static scratch.
///
/// Called at the top of the panic handler, before `panic_flush` drains the
/// ring. No pixels, no lock, no mutation -- one memcpy on a path that is
/// about to halt. Skipped entirely when no framebuffer is armed, which is
/// every headless boot, so a panic storm on a server pays nothing.
pub fn capture() {
    if snapshot().is_none() {
        return;
    }
    let buf = unsafe { &mut *SNAPSHOT.0.get() };
    let n = unsafe { crate::drivers::log_ring::peek_tail(buf) };
    SNAPSHOT_LEN.store(n, Ordering::Relaxed);
}

// DESIGN RULE: render and everything it calls acquires NO synchronization
// primitive -- not `Lock::lock`, not `Lock::try_lock`, not `RingGuard`, not
// `BackendGuard`. try_lock is banned too: it disables preemption on entry and
// its failure path re-enables it, which can dispatch the scheduler. No
// allocation, no `use alloc::`, no `&dyn`, no unwrap/expect/[]. Checked or
// saturating arithmetic only -- overflow-checks are on, so an overflow here is
// a panic inside a panic. Every framebuffer write is clamped to the published
// byte count. Stack budget is 256 bytes plus the one wrap array; the double
// fault path runs on IST1, which is 4096 bytes and already partly consumed by
// kernel_backtrace_safe.

/// Paint the captured report. Fatal paths only.
pub fn render() {
    if PAINTING.swap(true, Ordering::SeqCst) {
        return;
    }
    paint(Fill::Fatal, Source::Captured);
}

/// Repaint at a boot phase boundary, so a machine that wedges later still
/// shows how far it got. Converts "black screen" into "NVMe came up, xHCI
/// did not" for free, which is the only coverage there is for a hang that
/// never panics.
pub fn boot_checkpoint() {
    if SCREEN_OWNED_BY_USERLAND.load(Ordering::Relaxed) || PAINTING.load(Ordering::Relaxed) {
        return;
    }
    paint(Fill::Boot, Source::Live);
}

/// The fill colour carries "halted" versus "still booting" at zero cost, and
/// the fill itself is the proof the console ran *this* boot rather than a
/// stale frame surviving.
#[derive(Clone, Copy)]
enum Fill {
    Fatal,
    Boot,
}

/// Which bytes to paint. `SNAPSHOT_LEN != 0` means and only means "the panic
/// handler captured a report into SNAPSHOT" — a boot checkpoint must never
/// leave state that a later fatal render mistakes for one, which is exactly
/// the bug that showed up as a halted machine displaying its own boot log.
#[derive(Clone, Copy, PartialEq)]
enum Source {
    Captured,
    Live,
}

fn paint(fill: Fill, source: Source) {
    let Some(fb) = snapshot() else { return };
    if !mapped(&fb) {
        return;
    }

    let buf = unsafe { &mut *SNAPSHOT.0.get() };
    let captured = SNAPSHOT_LEN.load(Ordering::Relaxed).min(SNAPSHOT_CAP);
    let len = if source == Source::Captured && captured > 0 {
        captured
    } else {
        // Overwrites whatever was captured, so the marker goes first.
        SNAPSHOT_LEN.store(0, Ordering::Relaxed);
        unsafe { crate::drivers::log_ring::peek_tail(buf) }
    };
    let text = unsafe { &*SNAPSHOT.0.get() };

    fill_screen(
        &fb,
        match fill {
            Fill::Fatal => rgb(&fb, 0x60, 0x00, 0x00),
            Fill::Boot => 0,
        },
    );

    let cols = (fb.width as usize / GLYPH_W).min(MAX_COLS);
    let rows = (fb.height as usize / GLYPH_H).min(MAX_ROWS);
    if cols == 0 || rows == 0 {
        return;
    }

    // Wrap, do not clip: a backtrace line carrying a demangled Rust symbol
    // routinely exceeds 160 columns and the symbol is the single most valuable
    // token on the screen. One forward pass records where each display row
    // starts, into a ring holding the last MAX_ROWS+1 of them -- the only
    // array in this module and the one place the stack budget stretches.
    let mut row_start = [0u32; MAX_ROWS + 1];
    let mut last = 0usize;
    let mut col = 0usize;
    let mut i = 0usize;
    while i < len {
        let newline = text[i] == b'\n';
        i += 1;
        col += 1;
        if newline || col == cols {
            last += 1;
            row_start[last % (MAX_ROWS + 1)] = i as u32;
            col = 0;
        }
    }

    let draw = rows.min(last + 1);
    let first = last + 1 - draw;
    let white = rgb(&fb, 0xFF, 0xFF, 0xFF);
    let alert = rgb(&fb, 0xFF, 0x50, 0x50);

    for r in 0..draw {
        let start = row_start[(first + r) % (MAX_ROWS + 1)] as usize;
        let color = if has_alert(text, start, len, cols) { alert } else { white };
        let mut off = start;
        let mut c = 0;
        while c < cols && off < len {
            if text[off] == b'\n' {
                break;
            }
            draw_glyph(&fb, c, r, text[off], color);
            off += 1;
            c += 1;
        }
    }

    // The scanout is mapped write-back over a region firmware typically marks
    // WC or UC. QEMU does not care; a real panel does, and "the text is in L2
    // and never reached the screen" is a bug that would only ever appear on
    // metal. One instruction on a machine that is about to halt forever.
    unsafe { core::arch::asm!("wbinvd", options(nostack, preserves_flags)) };
}

/// Every fatal marker the kernel emits already matches this: `!!! PANIC !!!`,
/// `!!! DOUBLE PANIC !!!`, `!!! FAULT ... RECURSIVE`, the reentry line. Three
/// bytes per column is what makes a phone photo of 50 lines of text usable.
fn has_alert(text: &[u8], start: usize, len: usize, cols: usize) -> bool {
    let mut run = 0;
    let mut off = start;
    let mut c = 0;
    while c < cols && off < len {
        if text[off] == b'\n' {
            break;
        }
        run = if text[off] == b'!' { run + 1 } else { 0 };
        if run == 3 {
            return true;
        }
        off += 1;
        c += 1;
    }
    false
}

/// Whether the first and last framebuffer pages resolve in the *current* CR3.
///
/// Not `kernel_cr3()`: a panic in syscall context runs on a user address
/// space, which copies the kernel's top-half PML4 entries at creation. Shared
/// page directories propagate later mappings, but this proves it rather than
/// assuming it -- and it is what turns "the page tables are why we panicked"
/// into no console instead of a fault inside the panic handler.
fn mapped(fb: &Fb) -> bool {
    let base = fb.ptr as u64;
    let Some(last) = base.checked_add(fb.bytes.saturating_sub(1)) else {
        return false;
    };
    mm::paging::present_in_current_cr3(base) && mm::paging::present_in_current_cr3(last)
}

/// `pixel_format` is 0 for RGB and 1 for BGR (`bootloader/src/main.rs`). As a
/// little-endian u32 that is the byte order of the low three bytes.
fn rgb(fb: &Fb, r: u32, g: u32, b: u32) -> u32 {
    if fb.format == 0 {
        r | (g << 8) | (b << 16)
    } else {
        b | (g << 8) | (r << 16)
    }
}

#[inline]
fn put_pixel(fb: &Fb, x: usize, y: usize, color: u32) {
    let Some(row) = (y as u64).checked_mul(fb.stride_px as u64) else { return };
    let Some(idx) = row.checked_add(x as u64).and_then(|v| v.checked_mul(4)) else { return };
    if idx.saturating_add(4) > fb.bytes {
        return;
    }
    unsafe { core::ptr::write_volatile(fb.ptr.add(idx as usize) as *mut u32, color) };
}

/// Base pointer for a row, given that `len` pixels will be written from it.
/// `None` means the row does not fit the published byte count, which for a
/// left-to-right top-to-bottom walk means neither does any later row.
fn row_base(fb: &Fb, y: usize, len: usize) -> Option<*mut u32> {
    let start = (y as u64).checked_mul(fb.stride_px as u64)?.checked_mul(4)?;
    let end = start.checked_add((len as u64).checked_mul(4)?)?;
    (end <= fb.bytes).then(|| unsafe { fb.ptr.add(start as usize) as *mut u32 })
}

/// Erases whatever the compositor left behind, so nothing on screen is
/// ambiguous about which boot it came from.
///
/// Proves the clamp once per row rather than once per pixel: a boot
/// checkpoint repaints six times and a 2048x2048 panel is 4.2M pixels, so
/// per-pixel checked arithmetic here is the difference between a repaint
/// nobody notices and one that doubles boot time.
fn fill_screen(fb: &Fb, color: u32) {
    let width = fb.width as usize;
    for y in 0..fb.height as usize {
        let Some(row) = row_base(fb, y, width) else { return };
        for x in 0..width {
            unsafe { core::ptr::write_volatile(row.add(x), color) };
        }
    }
}

fn draw_glyph(fb: &Fb, cell_x: usize, cell_y: usize, byte: u8, color: u32) {
    let ch = match byte {
        b'\t' => b' ',
        0x20..=0x7E => byte,
        _ => b'.',
    };
    let base = (ch - 0x20) as usize * GLYPH_H;
    let ox = cell_x * GLYPH_W;
    let oy = cell_y * GLYPH_H;
    for (row, &bits) in FONT[base..base + GLYPH_H].iter().enumerate() {
        if bits == 0 {
            continue;
        }
        for bit in 0..GLYPH_W {
            if bits & (0x80 >> bit) != 0 {
                put_pixel(fb, ox + bit, oy + row, color);
            }
        }
    }
}
